class mythreadrunnable1 implements Runnable{
    public void run(){
        System.out.println("i am thread1 not a threat");
        System.out.println("i am thread1 not a threat");
        System.out.println("i am thread1 not a threat");
        System.out.println("i am thread1 not a threat");
        System.out.println("i am thread1 not a threat");
        System.out.println("i am thread1 not a threat");
        System.out.println("i am thread1 not a threat");
        System.out.println("i am thread1 not a threat");
        System.out.println("i am thread1 not a threat");
        System.out.println("i am thread1 not a threat");
        System.out.println("i am thread1 not a threat");
        System.out.println("i am thread1 not a threat");
        System.out.println("i am thread1 not a threat");
        System.out.println("i am thread1 not a threat");
        System.out.println("i am thread1 not a threat");
        System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");
 System.out.println("i am thread1 not a threat");

    }
}
class mythreadrunnable2 implements Runnable{
    public void run(){
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
        System.out.println("iam thread2 not threat2");
                
        

        



    }

}
public class threaddusingrunnableinterface {
    public static void main(String[] args) {
        mythreadrunnable1 bullet1=new  mythreadrunnable1();
        Thread gun1=new Thread(bullet1);
        mythreadrunnable2 bullet2=new mythreadrunnable2();
        Thread gun2=new Thread(bullet2);
        gun1.start();
        gun2.start();
        
    }
    
}
